package com.dataqin.common.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dataqin.common.model.SliceDB;

import com.dataqin.common.dao.SliceDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sliceDBDaoConfig;

    private final SliceDBDao sliceDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sliceDBDaoConfig = daoConfigMap.get(SliceDBDao.class).clone();
        sliceDBDaoConfig.initIdentityScope(type);

        sliceDBDao = new SliceDBDao(sliceDBDaoConfig, this);

        registerDao(SliceDB.class, sliceDBDao);
    }
    
    public void clear() {
        sliceDBDaoConfig.clearIdentityScope();
    }

    public SliceDBDao getSliceDBDao() {
        return sliceDBDao;
    }

}
