package com.dataqin.common.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dataqin.common.model.MobileFileDB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MOBILE_FILE_DB".
*/
public class MobileFileDBDao extends AbstractDao<MobileFileDB, String> {

    public static final String TABLENAME = "MOBILE_FILE_DB";

    /**
     * Properties of entity MobileFileDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property SourcePath = new Property(0, String.class, "sourcePath", true, "SOURCE_PATH");
        public final static Property UserId = new Property(1, String.class, "userId", false, "USER_ID");
        public final static Property Baoquan = new Property(2, String.class, "baoquan", false, "BAOQUAN");
        public final static Property Extras = new Property(3, String.class, "extras", false, "EXTRAS");
        public final static Property Index = new Property(4, int.class, "index", false, "INDEX");
        public final static Property FilePointer = new Property(5, long.class, "filePointer", false, "FILE_POINTER");
        public final static Property Upload = new Property(6, boolean.class, "upload", false, "UPLOAD");
        public final static Property Complete = new Property(7, boolean.class, "complete", false, "COMPLETE");
    }


    public MobileFileDBDao(DaoConfig config) {
        super(config);
    }
    
    public MobileFileDBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MOBILE_FILE_DB\" (" + //
                "\"SOURCE_PATH\" TEXT PRIMARY KEY NOT NULL ," + // 0: sourcePath
                "\"USER_ID\" TEXT," + // 1: userId
                "\"BAOQUAN\" TEXT," + // 2: baoquan
                "\"EXTRAS\" TEXT," + // 3: extras
                "\"INDEX\" INTEGER NOT NULL ," + // 4: index
                "\"FILE_POINTER\" INTEGER NOT NULL ," + // 5: filePointer
                "\"UPLOAD\" INTEGER NOT NULL ," + // 6: upload
                "\"COMPLETE\" INTEGER NOT NULL );"); // 7: complete
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MOBILE_FILE_DB\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MobileFileDB entity) {
        stmt.clearBindings();
 
        String sourcePath = entity.getSourcePath();
        if (sourcePath != null) {
            stmt.bindString(1, sourcePath);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
 
        String baoquan = entity.getBaoquan();
        if (baoquan != null) {
            stmt.bindString(3, baoquan);
        }
 
        String extras = entity.getExtras();
        if (extras != null) {
            stmt.bindString(4, extras);
        }
        stmt.bindLong(5, entity.getIndex());
        stmt.bindLong(6, entity.getFilePointer());
        stmt.bindLong(7, entity.getUpload() ? 1L: 0L);
        stmt.bindLong(8, entity.getComplete() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MobileFileDB entity) {
        stmt.clearBindings();
 
        String sourcePath = entity.getSourcePath();
        if (sourcePath != null) {
            stmt.bindString(1, sourcePath);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
 
        String baoquan = entity.getBaoquan();
        if (baoquan != null) {
            stmt.bindString(3, baoquan);
        }
 
        String extras = entity.getExtras();
        if (extras != null) {
            stmt.bindString(4, extras);
        }
        stmt.bindLong(5, entity.getIndex());
        stmt.bindLong(6, entity.getFilePointer());
        stmt.bindLong(7, entity.getUpload() ? 1L: 0L);
        stmt.bindLong(8, entity.getComplete() ? 1L: 0L);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public MobileFileDB readEntity(Cursor cursor, int offset) {
        MobileFileDB entity = new MobileFileDB( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // sourcePath
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // baoquan
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // extras
            cursor.getInt(offset + 4), // index
            cursor.getLong(offset + 5), // filePointer
            cursor.getShort(offset + 6) != 0, // upload
            cursor.getShort(offset + 7) != 0 // complete
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MobileFileDB entity, int offset) {
        entity.setSourcePath(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setUserId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBaoquan(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setExtras(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIndex(cursor.getInt(offset + 4));
        entity.setFilePointer(cursor.getLong(offset + 5));
        entity.setUpload(cursor.getShort(offset + 6) != 0);
        entity.setComplete(cursor.getShort(offset + 7) != 0);
     }
    
    @Override
    protected final String updateKeyAfterInsert(MobileFileDB entity, long rowId) {
        return entity.getSourcePath();
    }
    
    @Override
    public String getKey(MobileFileDB entity) {
        if(entity != null) {
            return entity.getSourcePath();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MobileFileDB entity) {
        return entity.getSourcePath() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
