package com.dataqin.common.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dataqin.common.model.SliceDB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SLICE_DB".
*/
public class SliceDBDao extends AbstractDao<SliceDB, String> {

    public static final String TABLENAME = "SLICE_DB";

    /**
     * Properties of entity SliceDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Baoquan = new Property(0, String.class, "baoquan", true, "BAOQUAN");
        public final static Property SourcePath = new Property(1, String.class, "sourcePath", false, "SOURCE_PATH");
        public final static Property UserId = new Property(2, String.class, "userId", false, "USER_ID");
        public final static Property Extras = new Property(3, String.class, "extras", false, "EXTRAS");
        public final static Property Complete = new Property(4, boolean.class, "complete", false, "COMPLETE");
        public final static Property Upload = new Property(5, boolean.class, "upload", false, "UPLOAD");
        public final static Property TmpPath = new Property(6, String.class, "tmpPath", false, "TMP_PATH");
        public final static Property SliceCount = new Property(7, int.class, "sliceCount", false, "SLICE_COUNT");
        public final static Property Index = new Property(8, int.class, "index", false, "INDEX");
        public final static Property EndPointer = new Property(9, long.class, "endPointer", false, "END_POINTER");
    }


    public SliceDBDao(DaoConfig config) {
        super(config);
    }
    
    public SliceDBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SLICE_DB\" (" + //
                "\"BAOQUAN\" TEXT PRIMARY KEY NOT NULL ," + // 0: baoquan
                "\"SOURCE_PATH\" TEXT," + // 1: sourcePath
                "\"USER_ID\" TEXT," + // 2: userId
                "\"EXTRAS\" TEXT," + // 3: extras
                "\"COMPLETE\" INTEGER NOT NULL ," + // 4: complete
                "\"UPLOAD\" INTEGER NOT NULL ," + // 5: upload
                "\"TMP_PATH\" TEXT," + // 6: tmpPath
                "\"SLICE_COUNT\" INTEGER NOT NULL ," + // 7: sliceCount
                "\"INDEX\" INTEGER NOT NULL ," + // 8: index
                "\"END_POINTER\" INTEGER NOT NULL );"); // 9: endPointer
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SLICE_DB\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SliceDB entity) {
        stmt.clearBindings();
 
        String baoquan = entity.getBaoquan();
        if (baoquan != null) {
            stmt.bindString(1, baoquan);
        }
 
        String sourcePath = entity.getSourcePath();
        if (sourcePath != null) {
            stmt.bindString(2, sourcePath);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(3, userId);
        }
 
        String extras = entity.getExtras();
        if (extras != null) {
            stmt.bindString(4, extras);
        }
        stmt.bindLong(5, entity.getComplete() ? 1L: 0L);
        stmt.bindLong(6, entity.getUpload() ? 1L: 0L);
 
        String tmpPath = entity.getTmpPath();
        if (tmpPath != null) {
            stmt.bindString(7, tmpPath);
        }
        stmt.bindLong(8, entity.getSliceCount());
        stmt.bindLong(9, entity.getIndex());
        stmt.bindLong(10, entity.getEndPointer());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SliceDB entity) {
        stmt.clearBindings();
 
        String baoquan = entity.getBaoquan();
        if (baoquan != null) {
            stmt.bindString(1, baoquan);
        }
 
        String sourcePath = entity.getSourcePath();
        if (sourcePath != null) {
            stmt.bindString(2, sourcePath);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(3, userId);
        }
 
        String extras = entity.getExtras();
        if (extras != null) {
            stmt.bindString(4, extras);
        }
        stmt.bindLong(5, entity.getComplete() ? 1L: 0L);
        stmt.bindLong(6, entity.getUpload() ? 1L: 0L);
 
        String tmpPath = entity.getTmpPath();
        if (tmpPath != null) {
            stmt.bindString(7, tmpPath);
        }
        stmt.bindLong(8, entity.getSliceCount());
        stmt.bindLong(9, entity.getIndex());
        stmt.bindLong(10, entity.getEndPointer());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public SliceDB readEntity(Cursor cursor, int offset) {
        SliceDB entity = new SliceDB( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // baoquan
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // sourcePath
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // userId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // extras
            cursor.getShort(offset + 4) != 0, // complete
            cursor.getShort(offset + 5) != 0, // upload
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // tmpPath
            cursor.getInt(offset + 7), // sliceCount
            cursor.getInt(offset + 8), // index
            cursor.getLong(offset + 9) // endPointer
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SliceDB entity, int offset) {
        entity.setBaoquan(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setSourcePath(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setExtras(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setComplete(cursor.getShort(offset + 4) != 0);
        entity.setUpload(cursor.getShort(offset + 5) != 0);
        entity.setTmpPath(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSliceCount(cursor.getInt(offset + 7));
        entity.setIndex(cursor.getInt(offset + 8));
        entity.setEndPointer(cursor.getLong(offset + 9));
     }
    
    @Override
    protected final String updateKeyAfterInsert(SliceDB entity, long rowId) {
        return entity.getBaoquan();
    }
    
    @Override
    public String getKey(SliceDB entity) {
        if(entity != null) {
            return entity.getBaoquan();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SliceDB entity) {
        return entity.getBaoquan() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
